auth:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/auth/**'

transactions:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/transactions/**'

kyc:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/kyc/**'

blockchain:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/blockchain/**'

dao:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/dao/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

testing:
  - changed-files:
      - any-glob-to-any-file:
          - 'test/**'

notifications:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/notifications/**'
